---
# -- (Optional) When using a custom network
networks:
  traefik-nw:
    external: true

services:
  traefik:
    image: docker.io/library/traefik:v3.0
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      # -- (Optional) Enable Dashboard, don't do in production
      - 9090:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/etc/traefik/
      - ./config/conf/:/etc/traefik/conf/
      - ./config/certs/:/etc/traefik/certs/
    # -- (Optional) When using Cloudflare as Cert Resolver
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    # -- (Optional) When using a custom network
    networks:
      - traefik-nw
    restart: unless-stopped